Refactor input parameters and add validation for required fields in Flyway CLI action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -23,26 +23,22 @@ inputs:
     description: 'The password to use for the target database'
     required: false
     default: ''
-  target_db_url:
-    description: 'The URL to use for the target database'
-    required: true
-    default: ''
-  custom_params:
-    description: 'Custom parameters to pass to Flyway CLI'
+  authenticate_flyway:
+    description: 'Disable authentication'
     required: false
+    default: 'true'
+  agree_to_eula:
+    description: 'Agree to the Flyway EULA'
+    required: false
+    default: 'true'
+  environment:
+    description: 'The environment to use for the Flyway CLI'
+    required: true
     default: ''
   check_drift_on_migration:
     description: 'Check for drift on migration'
     required: false
     default: 'false'
-  authenticate_flyway:
-    description: 'Disable authentication'
-    required: false
-    default: 'true'
-  environment:
-    description: 'The environment to use for the Flyway CLI'
-    required: false
-    default: ''
   publish_result:
     description: 'Publish the result of the migration'
     required: false
@@ -51,10 +47,25 @@ inputs:
     description: 'Clean the database build before migrating'
     required: false
     default: 'false'
+  custom_params:
+    description: 'Custom parameters to pass to Flyway CLI'
+    required: false
+    default: ''
 
 runs:
   using: 'composite'
   steps:
+    - name: 'Check inputs'
+      shell: pwsh
+      run: |
+        if (('${{ inputs.target_db_username }}' -ne '') -and ('${{ inputs.target_db_password }}' -eq '')) {
+          Write-Error "Target DB Password is required"
+          exit 1
+        }
+        if (('${{ inputs.flyway_email }}' -ne '') -and ('${{ inputs.flyway_token }}' -eq '')) {
+          Write-Error "Flyway Email and Token are required for authentication"
+          exit 1
+        }
     - name: 'Test if Flyway is already installed (Linux)'
       if: runner.os == 'Linux'
       shell: bash
@@ -91,7 +102,13 @@ runs:
           $flywayEmail = "${{ inputs.flyway_email }}"
           $flywayToken = "${{ inputs.flyway_token }}"
 
-          flyway auth -IAgreeToTheEula -email="${{ env.FLYWAY_EMAIL }}" -token="${{ env.FLYWAY_TOKEN }}"
+          if(${{ inputs.agree_to_eula }} == 'true') {
+            Write-Host "Agreeing to the Flyway EULA"
+            flyway auth -IAgreeToTheEula -email="${{ inputs.flyway_email }}" -token="${{ inputs.flyway_token }}"
+          } else {
+            flyway auth -email="${{ inputs.flyway_email }}" -token="${{ inputs.flyway_token }}"
+          }
+
           if ($LASTEXITCODE -ne 0) {
             Write-Error "Failed to authenticate to Flyway CLI"
             exit 1
@@ -100,29 +117,29 @@ runs:
           }
         }
 
-    - name: Clean DB Build
-      if: ${{ inputs.clean_db_build }} == 'true' && success() }}
-      shell: pwsh
-      run: |
-        Write-Host "Cleaning database build"
+    # - name: Clean DB Build
+    #   if: ${{ inputs.clean_db_build }} == 'true' && success() }}
+    #   shell: pwsh
+    #   run: |
+    #     Write-Host "Cleaning database build"
 
-        flyway info `
-          clean info `
-          -environment="${{ inputs.environment }}" `
-          -user="${{ inputs.target_db_username }}" `
-          -password="${{ inputs.target_db_password }}" `
-          -configFiles="${{ GITHUB.WORKSPACE }}/flyway.toml" `
-          -locations="filesystem:${{ GITHUB.WORKSPACE }}/migrations" `
-          -cleanDisabled='false' `
-          "-environments.${{ inputs.environment}}.provisioner=clean" `
-          ${{ inputs.custom_params }}
+    #     flyway info `
+    #       clean info `
+    #       -environment="${{ inputs.environment }}" `
+    #       -user="${{ inputs.target_db_username }}" `
+    #       -password="${{ inputs.target_db_password }}" `
+    #       -configFiles="${{ GITHUB.WORKSPACE }}/flyway.toml" `
+    #       -locations="filesystem:${{ GITHUB.WORKSPACE }}/migrations" `
+    #       -cleanDisabled='false' `
+    #       "-environments.${{ inputs.environment}}.provisioner=clean" `
+    #       ${{ inputs.custom_params }}
 
-        if ($LASTEXITCODE -ne 0) {
-          Write-Error "Failed to clean the database"
-          exit 1
-        } else {
-          Write-Host "Cleaned the database"
-        }
+    #     if ($LASTEXITCODE -ne 0) {
+    #       Write-Error "Failed to clean the database"
+    #       exit 1
+    #     } else {
+    #       Write-Host "Cleaned the database"
+    #     }
 
     - name: Migrate DB Build
       shell: pwsh
